# Generated by Django 5.2.11 on 2026-06-15 14:26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WannWarDasGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synced', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Wann war das?', max_length=200)),
                ('internal_description', models.TextField(blank=True, default='')),
                ('tutorial_enabled', models.BooleanField(default=False)),
                ('tutorial_title', models.CharField(blank=True, default='', max_length=200)),
                ('tutorial_text', models.TextField(blank=True, default='')),
                ('tutorial_active', models.BooleanField(default=False)),
                ('question_order', models.JSONField(blank=True, default=list)),
                ('room_code', models.CharField(blank=True, max_length=6, unique=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('active', 'Active'), ('inactive', 'Inactive'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='waiting', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('active_hub_session_code', models.CharField(blank=True, default='', max_length=16)),
                ('current_question_number', models.PositiveIntegerField(default=0)),
                ('current_question_is_tutorial', models.BooleanField(default=False)),
                ('question_state', models.CharField(choices=[('ready', 'Ready'), ('active', 'Active'), ('revealed', 'Revealed'), ('ended', 'Ended')], default='ready', max_length=20)),
                ('question_started_at', models.DateTimeField(blank=True, null=True)),
                ('question_ended_at', models.DateTimeField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_wann_war_das_games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WannWarDasParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synced', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('hub_session_code', models.CharField(blank=True, default='', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_score', models.IntegerField(default=0)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='wann_war_das.wannwardasgame')),
            ],
            options={
                'ordering': ['-total_score', 'name'],
                'unique_together': {('quiz', 'name', 'hub_session_code')},
            },
        ),
        migrations.CreateModel(
            name='WannWarDasQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synced', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_text', models.TextField()),
                ('correct_answer', models.FloatField()),
                ('unit', models.CharField(blank=True, default='Jahr', max_length=40)),
                ('start_tolerance', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('tolerance_increment', models.FloatField(default=1)),
                ('seconds_per_step', models.PositiveIntegerField(default=5)),
                ('max_tolerance', models.FloatField(default=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_points', models.PositiveIntegerField(default=10)),
                ('min_points', models.PositiveIntegerField(default=1)),
                ('time_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('explanation', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_wann_war_das_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='wannwardasgame',
            name='current_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_in_games', to='wann_war_das.wannwardasquestion'),
        ),
        migrations.AddField(
            model_name='wannwardasgame',
            name='selected_questions',
            field=models.ManyToManyField(blank=True, related_name='games', to='wann_war_das.wannwardasquestion'),
        ),
        migrations.AddField(
            model_name='wannwardasgame',
            name='tutorial_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutorial_in_games', to='wann_war_das.wannwardasquestion'),
        ),
        migrations.CreateModel(
            name='WannWarDasAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synced', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hub_session_code', models.CharField(blank=True, default='', max_length=16)),
                ('raw_answer', models.CharField(blank=True, default='', max_length=120)),
                ('user_answer', models.FloatField(blank=True, null=True)),
                ('is_numeric', models.BooleanField(default=False)),
                ('absolute_deviation', models.FloatField(blank=True, null=True)),
                ('tolerance_at_submit', models.FloatField(default=0)),
                ('step_index', models.PositiveIntegerField(default=0)),
                ('points_earned', models.IntegerField(default=0)),
                ('is_correct', models.BooleanField(default=False)),
                ('time_taken', models.FloatField(default=0)),
                ('is_tutorial', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='wann_war_das.wannwardasgame')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='wann_war_das.wannwardasparticipant')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='wann_war_das.wannwardasquestion')),
            ],
            options={
                'ordering': ['submitted_at', 'id'],
                'indexes': [models.Index(fields=['quiz', 'hub_session_code'], name='wann_war_da_quiz_id_4321fe_idx'), models.Index(fields=['question', 'hub_session_code'], name='wann_war_da_questio_729377_idx')],
                'unique_together': {('quiz', 'participant', 'question', 'hub_session_code')},
            },
        ),
    ]
