# Generated by Django 5.2.11 on 2026-06-23 15:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HostPointsGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synced', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Host-Punktevergabe', max_length=200)),
                ('internal_description', models.TextField(blank=True, default='')),
                ('tutorial_enabled', models.BooleanField(default=False)),
                ('tutorial_title', models.CharField(blank=True, default='', max_length=200)),
                ('tutorial_text', models.TextField(blank=True, default='')),
                ('tutorial_active', models.BooleanField(default=False)),
                ('room_code', models.CharField(blank=True, max_length=6, unique=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('active', 'Active'), ('inactive', 'Inactive'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='waiting', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('active_hub_session_code', models.CharField(blank=True, default='', max_length=16)),
                ('current_round_number', models.PositiveIntegerField(default=0)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_host_points_games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HostPointsParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synced', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('hub_session_code', models.CharField(blank=True, default='', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_score', models.IntegerField(default=0)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='host_points.hostpointsgame')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('quiz', 'name', 'hub_session_code')},
            },
        ),
        migrations.CreateModel(
            name='HostPointsAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synced', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hub_session_code', models.CharField(blank=True, default='', max_length=16)),
                ('round_number', models.PositiveIntegerField(default=1)),
                ('points_delta', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='host_points.hostpointsgame')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='host_points.hostpointsparticipant')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['quiz', 'hub_session_code'], name='host_points_quiz_id_c3b39c_idx'), models.Index(fields=['participant', 'round_number'], name='host_points_partici_fc1744_idx')],
            },
        ),
    ]
