# Generated by Django 5.2.11 on 2026-07-24 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorting_ladder', '0012_sortingladdersession_reveal_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='SortingPendingRoundSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synced', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('round_number', models.PositiveIntegerField()),
                ('ordered_item_ids', models.JSONField(blank=True, default=list)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_round_selections', to='sorting_ladder.sortingladderparticipant')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_round_selections', to='sorting_ladder.sortingquestion')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_round_selections', to='sorting_ladder.sortingladdergame')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('quiz', 'participant', 'question', 'round_number'), name='unique_sorting_pending_round_selection')],
            },
        ),
    ]
