# Generated by Django 5.2.11 on 2026-06-08 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('where_is_this', '0011_alter_wherequiz_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='wherequiz',
            name='tutorial_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutorial_in_quizzes', to='where_is_this.wherequestion'),
        ),
    ]
