# Generated by Django 5.2.11 on 2026-06-16 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('where_is_this', '0012_wherequiz_tutorial_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='whereanswer',
            name='rank_position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whereanswer',
            name='scoring_mode',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='whereanswer',
            name='x_norm',
            field=models.FloatField(blank=True, help_text='Normalized X coordinate on the Web-Mercator map', null=True),
        ),
        migrations.AddField(
            model_name='whereanswer',
            name='y_norm',
            field=models.FloatField(blank=True, help_text='Normalized Y coordinate on the Web-Mercator map', null=True),
        ),
        migrations.AddField(
            model_name='whereanswer',
            name='zone_label',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='wherequestion',
            name='map_type',
            field=models.CharField(choices=[('world_mercator', 'Weltkarte')], default='world_mercator', max_length=32),
        ),
        migrations.AddField(
            model_name='wherequiz',
            name='scoring_mode',
            field=models.CharField(choices=[('zones', 'Zielzonen'), ('rank', 'Ranking')], default='zones', max_length=16),
        ),
        migrations.CreateModel(
            name='WhereDistanceZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synced', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('min_distance_km', models.FloatField(default=0)),
                ('max_distance_km', models.FloatField()),
                ('points', models.PositiveIntegerField(default=0)),
                ('label', models.CharField(blank=True, default='', max_length=100)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distance_zones', to='where_is_this.wherequestion')),
            ],
            options={
                'ordering': ['min_distance_km', 'max_distance_km', 'id'],
            },
        ),
    ]
