# Generated by Django 5.2.11 on 2026-06-08 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('black_jack_quiz', '0015_alter_blackjackquiz_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='blackjackquiz',
            name='tutorial_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutorial_in_quizzes', to='black_jack_quiz.blackjackquestion'),
        ),
    ]
