# Generated by Codex on 2026-06-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('black_jack_quiz', '0016_blackjackquiz_tutorial_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blackjackquiz',
            name='tutorial_question',
        ),
        migrations.AddField(
            model_name='blackjackquiz',
            name='tutorial_set_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
