# Generated by Django 5.2.11 on 2026-04-22 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizGame', '0010_quizquestion_double_answer_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='answer_label_1',
            field=models.CharField(blank=True, default='', help_text='For short answer: label for field 1.', max_length=120),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='answer_label_2',
            field=models.CharField(blank=True, default='', help_text='For short answer: label for field 2.', max_length=120),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='answer_label_3',
            field=models.CharField(blank=True, default='', help_text='For short answer: label for field 3.', max_length=120),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='answer_label_4',
            field=models.CharField(blank=True, default='', help_text='For short answer: label for field 4.', max_length=120),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='correct_answer_3',
            field=models.CharField(blank=True, default='', help_text='For short answer: the correct answer text for field 3.', max_length=500),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='correct_answer_4',
            field=models.CharField(blank=True, default='', help_text='For short answer: the correct answer text for field 4.', max_length=500),
        ),
    ]
