# Generated by Django 5.2.11 on 2026-05-19 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizGame', '0013_quiz_tutorial_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('active', 'Active'), ('inactive', 'Inactive'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='waiting', max_length=20),
        ),
    ]
