# Generated by Django 5.2.11 on 2026-05-23 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_hub', '0007_alter_hubgamestep_game_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hubgamestep',
            name='game_key',
            field=models.CharField(choices=[('quiz', 'QuizGame'), ('assign', 'Assign'), ('estimation', 'Estimation'), ('where', 'Where Is This'), ('who', 'Who Is Lying'), ('who_that', 'Who Is That'), ('blackjack', 'Black Jack Quiz'), ('sorting_ladder', 'Sorting Ladder'), ('clue_rush', 'Clue Rush'), ('wer_weiss_mehr', 'Wer weiß mehr?')], max_length=20),
        ),
    ]
