# Generated by Django 5.2.11 on 2026-05-29 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_hub', '0008_alter_hubgamestep_game_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubsession',
            name='overall_scoring_mode',
            field=models.CharField(choices=[('simple', 'Einfach'), ('ranking', 'Ranking')], default='simple', max_length=20),
        ),
        migrations.AddField(
            model_name='hubsession',
            name='overall_weighting_mode',
            field=models.CharField(choices=[('none', 'Keine Gewichtung'), ('linear_cap', 'Lineare Gewichtung mit Cap')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='hubsession',
            name='weighting_cap',
            field=models.FloatField(default=2.0),
        ),
        migrations.AddField(
            model_name='hubsession',
            name='weighting_step',
            field=models.FloatField(default=0.15),
        ),
    ]
