# Generated by Django 5.2.11 on 2026-05-30 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_hub', '0009_hubsession_overall_scoring_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubparticipant',
            name='check_in_excluded_by_host',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hubparticipant',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hubparticipant',
            name='scoring_eligible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hubsession',
            name='check_in_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hubsession',
            name='check_in_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hubsession',
            name='check_in_status',
            field=models.CharField(choices=[('not_started', 'Nicht gestartet'), ('open', 'Offen'), ('completed', 'Abgeschlossen')], default='not_started', max_length=20),
        ),
        migrations.AddField(
            model_name='hubsession',
            name='locked_participant_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
