# Generated by Django 5.2.11 on 2026-06-02 20:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_hub', '0010_hubparticipant_check_in_excluded_by_host_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubparticipant',
            name='left_permanently_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='HubGameParticipantSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synced', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('included_in_scoring', models.BooleanField(default=True)),
                ('active_player', models.BooleanField(default=True)),
                ('auto_zero', models.BooleanField(default=False)),
                ('reason', models.CharField(choices=[('active', 'Aktiv'), ('left_permanently', 'Dauerhaft verlassen'), ('late_not_yet_eligible', 'Late Join noch nicht zugelassen'), ('excluded', 'Ausgeschlossen')], default='active', max_length=40)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('game_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_snapshots', to='games_hub.hubgamestep')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_snapshots', to='games_hub.hubparticipant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_snapshots', to='games_hub.hubsession')),
            ],
            options={
                'ordering': ['game_step__order', 'participant__joined_at', 'participant__nickname'],
                'unique_together': {('game_step', 'participant')},
            },
        ),
    ]
