# Generated by Django 5.2.11 on 2026-06-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_hub', '0011_hubparticipant_left_permanently_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gamevote',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='gamevote',
            name='voting_round',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hubsession',
            name='current_voting_round',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hubsession',
            name='voting_closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hubsession',
            name='voting_mode',
            field=models.CharField(choices=[('off', 'Aus'), ('normal', 'Normales Voting'), ('loser', 'Verlierer-Voting'), ('winner', 'Sieger-Voting')], default='off', max_length=20),
        ),
        migrations.AddField(
            model_name='hubsession',
            name='voting_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hubsession',
            name='voting_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='gamevote',
            unique_together={('session', 'voting_round', 'participant_nickname')},
        ),
    ]
