# Generated by Codex on 2026-06-06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_hub', '0012_alter_gamevote_unique_together_gamevote_voting_round_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HubGameTutorialRuntime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synced', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('text', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('game_step', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutorial_runtime', to='games_hub.hubgamestep')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_tutorial_runtimes', to='games_hub.hubsession')),
            ],
            options={
                'ordering': ['game_step__order'],
            },
        ),
        migrations.CreateModel(
            name='HubGameTutorialAcknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synced', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('runtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgements', to='games_hub.hubgametutorialruntime')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorial_acknowledgements', to='games_hub.hubgameparticipantsnapshot')),
            ],
            options={
                'ordering': ['snapshot__participant__joined_at', 'snapshot__participant__nickname'],
                'unique_together': {('runtime', 'snapshot')},
            },
        ),
    ]
