# Generated by Django 5.2.11 on 2026-07-24 16:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_hub', '0018_hubreadinesscheck_hubreadinessparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubsession',
            name='lobby_return_countdown_duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hubsession',
            name='lobby_return_countdown_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='GameRuntimeState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_key', models.CharField(max_length=160, unique=True)),
                ('game_key', models.CharField(max_length=32)),
                ('room_code', models.CharField(max_length=32)),
                ('game_instance_id', models.CharField(blank=True, default='', max_length=64)),
                ('state_revision', models.PositiveBigIntegerField(default=0)),
                ('context_revision', models.PositiveBigIntegerField(default=0)),
                ('phase', models.CharField(blank=True, default='', max_length=64)),
                ('current_question_id', models.CharField(blank=True, default='', max_length=64)),
                ('current_round_id', models.CharField(blank=True, default='', max_length=64)),
                ('current_set_id', models.CharField(blank=True, default='', max_length=64)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('public_snapshot', models.JSONField(blank=True, default=dict)),
                ('context_fingerprint', models.CharField(blank=True, default='', max_length=64)),
                ('display_fingerprint', models.CharField(blank=True, default='', max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runtime_states', to='games_hub.hubgamestep')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runtime_states', to='games_hub.hubsession')),
            ],
        ),
        migrations.CreateModel(
            name='HubSocketConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('channel_name', models.CharField(max_length=255, unique=True)),
                ('scope_kind', models.CharField(default='game', max_length=16)),
                ('game_key', models.CharField(blank=True, default='', max_length=32)),
                ('room_code', models.CharField(blank=True, default='', max_length=32)),
                ('connected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socket_connections', to='games_hub.hubparticipant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socket_connections', to='games_hub.hubsession')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedClientAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_key', models.CharField(max_length=128)),
                ('client_action_id', models.UUIDField()),
                ('action_type', models.CharField(max_length=64)),
                ('state_revision', models.PositiveBigIntegerField()),
                ('game_instance_id', models.CharField(blank=True, default='', max_length=64)),
                ('question_id', models.CharField(blank=True, default='', max_length=64)),
                ('round_id', models.CharField(blank=True, default='', max_length=64)),
                ('set_id', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_actions', to='games_hub.hubparticipant')),
                ('runtime_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_actions', to='games_hub.gameruntimestate')),
            ],
        ),
        migrations.AddIndex(
            model_name='gameruntimestate',
            index=models.Index(fields=['game_key', 'room_code'], name='games_hub_g_game_ke_f10690_idx'),
        ),
        migrations.AddIndex(
            model_name='gameruntimestate',
            index=models.Index(fields=['session', 'game_key'], name='games_hub_g_session_0b4b6a_idx'),
        ),
        migrations.AddIndex(
            model_name='hubsocketconnection',
            index=models.Index(fields=['participant', 'disconnected_at', 'last_seen'], name='games_hub_h_partici_f6e7be_idx'),
        ),
        migrations.AddIndex(
            model_name='hubsocketconnection',
            index=models.Index(fields=['session', 'game_key', 'room_code'], name='games_hub_h_session_1e04e1_idx'),
        ),
        migrations.AddIndex(
            model_name='processedclientaction',
            index=models.Index(fields=['runtime_state', 'participant_key', 'created_at'], name='games_hub_p_runtime_d55dca_idx'),
        ),
        migrations.AddConstraint(
            model_name='processedclientaction',
            constraint=models.UniqueConstraint(fields=('runtime_state', 'participant_key', 'client_action_id'), name='unique_runtime_participant_action'),
        ),
    ]
