# Generated by Django 5.2.11 on 2026-05-17 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clue_rush', '0010_backfill_clueanswer_submission_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluerushgame',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('active', 'Active'), ('inactive', 'Inactive'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='waiting', max_length=20),
        ),
    ]
