# Generated by Django 5.2.11 on 2026-05-26 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clue_rush', '0011_alter_cluerushgame_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CluePendingInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synced', models.BooleanField(default=False)),
                ('answer_text', models.CharField(blank=True, default='', max_length=200)),
                ('submitted_clue_number', models.PositiveIntegerField(default=0)),
                ('total_clues_at_input', models.PositiveIntegerField(default=0)),
                ('time_taken', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_inputs', to='clue_rush.cluerushparticipant')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_inputs', to='clue_rush.cluequestion')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_inputs', to='clue_rush.cluerushgame')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('quiz', 'participant', 'question')},
            },
        ),
    ]
