# Generated by Django 5.2.11 on 2026-06-08 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clue_rush', '0012_cluependinginput'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluerushgame',
            name='tutorial_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutorial_in_games', to='clue_rush.cluequestion'),
        ),
    ]
