# Generated by Django 5.2.11 on 2026-05-23 00:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WerWeissMehrGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synced', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Wer weiß mehr', max_length=200)),
                ('internal_description', models.TextField(blank=True, default='')),
                ('tutorial_enabled', models.BooleanField(default=False)),
                ('tutorial_title', models.CharField(blank=True, default='', max_length=200)),
                ('tutorial_text', models.TextField(blank=True, default='')),
                ('tutorial_active', models.BooleanField(default=False)),
                ('question_order', models.JSONField(blank=True, default=list)),
                ('room_code', models.CharField(blank=True, max_length=4, unique=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('active', 'Active'), ('inactive', 'Inactive'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='waiting', max_length=20)),
                ('max_participants', models.IntegerField(default=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_wer_weiss_mehr_games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WerWeissMehrParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synced', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('total_score', models.IntegerField(default=0)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('hub_session_code', models.CharField(blank=True, db_index=True, max_length=16, null=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='wer_weiss_mehr.werweissmehrgame')),
            ],
            options={
                'ordering': ['-total_score', 'name'],
                'unique_together': {('quiz', 'name', 'hub_session_code')},
            },
        ),
        migrations.CreateModel(
            name='WerWeissMehrQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synced', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_text', models.TextField()),
                ('round_time_limit', models.PositiveIntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_wer_weiss_mehr_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='werweissmehrgame',
            name='current_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_in_games', to='wer_weiss_mehr.werweissmehrquestion'),
        ),
        migrations.AddField(
            model_name='werweissmehrgame',
            name='selected_questions',
            field=models.ManyToManyField(blank=True, related_name='games', to='wer_weiss_mehr.werweissmehrquestion'),
        ),
        migrations.CreateModel(
            name='WerWeissMehrAnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synced', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canonical_text', models.CharField(max_length=255)),
                ('normalized_text', models.CharField(blank=True, db_index=True, max_length=255)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='wer_weiss_mehr.werweissmehrquestion')),
            ],
            options={
                'ordering': ['sort_order', 'canonical_text', 'id'],
                'unique_together': {('question', 'normalized_text')},
            },
        ),
        migrations.CreateModel(
            name='WerWeissMehrSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synced', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_round', models.PositiveIntegerField(default=0)),
                ('phase', models.CharField(choices=[('idle', 'Idle'), ('round_active', 'Round active'), ('review', 'Review'), ('set_completed', 'Set completed')], default='idle', max_length=24)),
                ('round_start_time', models.DateTimeField(blank=True, null=True)),
                ('round_end_time', models.DateTimeField(blank=True, null=True)),
                ('time_limit_seconds', models.PositiveIntegerField(default=30)),
                ('completed_question_ids', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='wer_weiss_mehr.werweissmehrgame')),
                ('revealed_answers', models.ManyToManyField(blank=True, related_name='revealed_in_sessions', to='wer_weiss_mehr.werweissmehransweroption')),
            ],
            options={
                'ordering': ['quiz_id'],
            },
        ),
        migrations.CreateModel(
            name='WerWeissMehrPendingInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synced', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('round_number', models.PositiveIntegerField()),
                ('answer_text', models.TextField(blank=True, default='')),
                ('normalized_answer', models.CharField(blank=True, default='', max_length=255)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_inputs', to='wer_weiss_mehr.werweissmehrparticipant')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_inputs', to='wer_weiss_mehr.werweissmehrgame')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_inputs', to='wer_weiss_mehr.werweissmehrquestion')),
            ],
            options={
                'unique_together': {('quiz', 'participant', 'question', 'round_number')},
            },
        ),
        migrations.CreateModel(
            name='WerWeissMehrParticipantState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synced', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_eliminated', models.BooleanField(default=False)),
                ('survived_rounds', models.PositiveIntegerField(default=0)),
                ('last_status', models.CharField(blank=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_states', to='wer_weiss_mehr.werweissmehrparticipant')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_states', to='wer_weiss_mehr.werweissmehrgame')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_states', to='wer_weiss_mehr.werweissmehrquestion')),
            ],
            options={
                'ordering': ['participant__name'],
                'unique_together': {('quiz', 'participant', 'question')},
            },
        ),
        migrations.CreateModel(
            name='WerWeissMehrRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synced', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('round_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('review', 'Review'), ('completed', 'Completed')], default='active', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('revealed_answer_ids_at_start', models.JSONField(blank=True, default=list)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='wer_weiss_mehr.werweissmehrquestion')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='wer_weiss_mehr.werweissmehrgame')),
            ],
            options={
                'ordering': ['round_number'],
                'unique_together': {('quiz', 'question', 'round_number')},
            },
        ),
        migrations.CreateModel(
            name='WerWeissMehrRoundResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synced', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('round_number', models.PositiveIntegerField()),
                ('answer_text', models.TextField(blank=True, default='')),
                ('normalized_answer', models.CharField(blank=True, default='', max_length=255)),
                ('auto_status', models.CharField(choices=[('correct', 'Correct'), ('wrong', 'Wrong'), ('empty', 'Empty'), ('already_revealed', 'Already revealed'), ('unclear', 'Unclear'), ('manual_corrected', 'Manual corrected')], default='empty', max_length=32)),
                ('final_status', models.CharField(choices=[('correct', 'Correct'), ('wrong', 'Wrong'), ('empty', 'Empty'), ('already_revealed', 'Already revealed'), ('unclear', 'Unclear'), ('manual_corrected', 'Manual corrected')], default='empty', max_length=32)),
                ('is_correct', models.BooleanField(default=False)),
                ('is_manual_override', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('matched_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='wer_weiss_mehr.werweissmehransweroption')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='wer_weiss_mehr.werweissmehrparticipant')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='wer_weiss_mehr.werweissmehrquestion')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='wer_weiss_mehr.werweissmehrgame')),
            ],
            options={
                'ordering': ['participant__name', 'round_number'],
                'unique_together': {('quiz', 'participant', 'question', 'round_number')},
            },
        ),
    ]
