# Generated by Django 5.2.11 on 2026-05-25 23:53

from django.db import migrations, models


def normalize_legacy_response_statuses(apps, schema_editor):
    response_model = apps.get_model('wer_weiss_mehr', 'WerWeissMehrRoundResponse')
    response_model.objects.filter(auto_status__in=['empty', 'already_revealed', 'unclear']).update(auto_status='wrong')
    response_model.objects.filter(final_status__in=['empty', 'already_revealed', 'unclear']).update(final_status='wrong')


class Migration(migrations.Migration):

    dependencies = [
        ('wer_weiss_mehr', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(normalize_legacy_response_statuses, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='werweissmehrroundresponse',
            name='auto_status',
            field=models.CharField(choices=[('correct', 'Correct'), ('wrong', 'Wrong'), ('manual_corrected', 'Manual corrected')], default='wrong', max_length=32),
        ),
        migrations.AlterField(
            model_name='werweissmehrroundresponse',
            name='final_status',
            field=models.CharField(choices=[('correct', 'Correct'), ('wrong', 'Wrong'), ('manual_corrected', 'Manual corrected')], default='wrong', max_length=32),
        ),
    ]
