# Generated by Django 5.2.11 on 2026-06-08 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wer_weiss_mehr', '0002_alter_werweissmehrroundresponse_auto_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='werweissmehrgame',
            name='tutorial_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutorial_in_games', to='wer_weiss_mehr.werweissmehrquestion'),
        ),
    ]
