# Generated by Django 5.2.11 on 2026-06-14 16:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuzzerGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synced', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Buzzer', max_length=200)),
                ('internal_description', models.TextField(blank=True, default='')),
                ('tutorial_enabled', models.BooleanField(default=False)),
                ('tutorial_title', models.CharField(blank=True, default='', max_length=200)),
                ('tutorial_text', models.TextField(blank=True, default='')),
                ('tutorial_active', models.BooleanField(default=False)),
                ('room_code', models.CharField(blank=True, max_length=6, unique=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('active', 'Active'), ('inactive', 'Inactive'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='waiting', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('points_per_correct', models.PositiveIntegerField(default=1)),
                ('planned_rounds', models.PositiveIntegerField(blank=True, null=True)),
                ('active_hub_session_code', models.CharField(blank=True, default='', max_length=16)),
                ('current_round_number', models.PositiveIntegerField(default=0)),
                ('round_state', models.CharField(choices=[('ready', 'Ready'), ('open', 'Buzzer open'), ('locked', 'Buzz locked'), ('answered', 'Answered'), ('ended', 'Ended')], default='ready', max_length=20)),
                ('buzzer_open', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_buzzer_games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BuzzerParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synced', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('hub_session_code', models.CharField(blank=True, default='', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_score', models.IntegerField(default=0)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='buzzer.buzzergame')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('quiz', 'name', 'hub_session_code')},
            },
        ),
        migrations.AddField(
            model_name='buzzergame',
            name='current_buzz_participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='buzzer.buzzerparticipant'),
        ),
        migrations.CreateModel(
            name='BuzzerRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synced', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hub_session_code', models.CharField(blank=True, default='', max_length=16)),
                ('round_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('open', 'Buzzer open'), ('locked', 'Buzz locked'), ('answered', 'Answered'), ('ended', 'Ended')], default='ready', max_length=20)),
                ('buzzer_open', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('correct_participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correct_buzzer_rounds', to='buzzer.buzzerparticipant')),
                ('current_buzz_participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_buzzer_rounds', to='buzzer.buzzerparticipant')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='buzzer.buzzergame')),
            ],
            options={
                'ordering': ['round_number'],
                'unique_together': {('quiz', 'hub_session_code', 'round_number')},
            },
        ),
        migrations.AddField(
            model_name='buzzergame',
            name='current_round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='buzzer.buzzerround'),
        ),
        migrations.CreateModel(
            name='BuzzerBuzz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synced', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hub_session_code', models.CharField(blank=True, default='', max_length=16)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('correct', 'Correct'), ('wrong', 'Wrong')], default='accepted', max_length=20)),
                ('is_first', models.BooleanField(default=False)),
                ('buzzed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buzzes', to='buzzer.buzzergame')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buzzes', to='buzzer.buzzerparticipant')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buzzes', to='buzzer.buzzerround')),
            ],
            options={
                'ordering': ['round', 'sequence', 'buzzed_at'],
                'indexes': [models.Index(fields=['quiz', 'hub_session_code'], name='buzzer_buzz_quiz_id_9d7d89_idx'), models.Index(fields=['round', 'status'], name='buzzer_buzz_round_i_0b3e49_idx')],
            },
        ),
    ]
